// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class AppFlow
{
	private final IMendixObject appFlowMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.AppFlow";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HasCar("HasCar"),
		HasCoachwork("HasCoachwork"),
		HasColorCar("HasColorCar"),
		Selection_Car("MyFirstModule.Selection_Car"),
		Selection_Coachwork("MyFirstModule.Selection_Coachwork"),
		Selection_CarColor("MyFirstModule.Selection_CarColor"),
		AppFlow_Account("MyFirstModule.AppFlow_Account");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public AppFlow(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.AppFlow"));
	}

	protected AppFlow(IContext context, IMendixObject appFlowMendixObject)
	{
		if (appFlowMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.AppFlow", appFlowMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.AppFlow");

		this.appFlowMendixObject = appFlowMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AppFlow.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.AppFlow initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.AppFlow.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.AppFlow initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.AppFlow(context, mendixObject);
	}

	public static myfirstmodule.proxies.AppFlow load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.AppFlow.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.AppFlow> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.AppFlow> result = new java.util.ArrayList<myfirstmodule.proxies.AppFlow>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.AppFlow" + xpathConstraint))
			result.add(myfirstmodule.proxies.AppFlow.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of HasCar
	 */
	public final Boolean getHasCar()
	{
		return getHasCar(getContext());
	}

	/**
	 * @param context
	 * @return value of HasCar
	 */
	public final Boolean getHasCar(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.HasCar.toString());
	}

	/**
	 * Set value of HasCar
	 * @param hascar
	 */
	public final void setHasCar(Boolean hascar)
	{
		setHasCar(getContext(), hascar);
	}

	/**
	 * Set value of HasCar
	 * @param context
	 * @param hascar
	 */
	public final void setHasCar(IContext context, Boolean hascar)
	{
		getMendixObject().setValue(context, MemberNames.HasCar.toString(), hascar);
	}

	/**
	 * @return value of HasCoachwork
	 */
	public final Boolean getHasCoachwork()
	{
		return getHasCoachwork(getContext());
	}

	/**
	 * @param context
	 * @return value of HasCoachwork
	 */
	public final Boolean getHasCoachwork(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.HasCoachwork.toString());
	}

	/**
	 * Set value of HasCoachwork
	 * @param hascoachwork
	 */
	public final void setHasCoachwork(Boolean hascoachwork)
	{
		setHasCoachwork(getContext(), hascoachwork);
	}

	/**
	 * Set value of HasCoachwork
	 * @param context
	 * @param hascoachwork
	 */
	public final void setHasCoachwork(IContext context, Boolean hascoachwork)
	{
		getMendixObject().setValue(context, MemberNames.HasCoachwork.toString(), hascoachwork);
	}

	/**
	 * @return value of HasColorCar
	 */
	public final Boolean getHasColorCar()
	{
		return getHasColorCar(getContext());
	}

	/**
	 * @param context
	 * @return value of HasColorCar
	 */
	public final Boolean getHasColorCar(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.HasColorCar.toString());
	}

	/**
	 * Set value of HasColorCar
	 * @param hascolorcar
	 */
	public final void setHasColorCar(Boolean hascolorcar)
	{
		setHasColorCar(getContext(), hascolorcar);
	}

	/**
	 * Set value of HasColorCar
	 * @param context
	 * @param hascolorcar
	 */
	public final void setHasColorCar(IContext context, Boolean hascolorcar)
	{
		getMendixObject().setValue(context, MemberNames.HasColorCar.toString(), hascolorcar);
	}

	/**
	 * @return value of Selection_Car
	 */
	public final myfirstmodule.proxies.Car getSelection_Car() throws CoreException
	{
		return getSelection_Car(getContext());
	}

	/**
	 * @param context
	 * @return value of Selection_Car
	 */
	public final myfirstmodule.proxies.Car getSelection_Car(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Car result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Selection_Car.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Car.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Selection_Car
	 * @param selection_car
	 */
	public final void setSelection_Car(myfirstmodule.proxies.Car selection_car)
	{
		setSelection_Car(getContext(), selection_car);
	}

	/**
	 * Set value of Selection_Car
	 * @param context
	 * @param selection_car
	 */
	public final void setSelection_Car(IContext context, myfirstmodule.proxies.Car selection_car)
	{
		if (selection_car == null)
			getMendixObject().setValue(context, MemberNames.Selection_Car.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Selection_Car.toString(), selection_car.getMendixObject().getId());
	}

	/**
	 * @return value of Selection_Coachwork
	 */
	public final myfirstmodule.proxies.Coachwork getSelection_Coachwork() throws CoreException
	{
		return getSelection_Coachwork(getContext());
	}

	/**
	 * @param context
	 * @return value of Selection_Coachwork
	 */
	public final myfirstmodule.proxies.Coachwork getSelection_Coachwork(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Coachwork result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Selection_Coachwork.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Coachwork.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Selection_Coachwork
	 * @param selection_coachwork
	 */
	public final void setSelection_Coachwork(myfirstmodule.proxies.Coachwork selection_coachwork)
	{
		setSelection_Coachwork(getContext(), selection_coachwork);
	}

	/**
	 * Set value of Selection_Coachwork
	 * @param context
	 * @param selection_coachwork
	 */
	public final void setSelection_Coachwork(IContext context, myfirstmodule.proxies.Coachwork selection_coachwork)
	{
		if (selection_coachwork == null)
			getMendixObject().setValue(context, MemberNames.Selection_Coachwork.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Selection_Coachwork.toString(), selection_coachwork.getMendixObject().getId());
	}

	/**
	 * @return value of Selection_CarColor
	 */
	public final myfirstmodule.proxies.CarColor getSelection_CarColor() throws CoreException
	{
		return getSelection_CarColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Selection_CarColor
	 */
	public final myfirstmodule.proxies.CarColor getSelection_CarColor(IContext context) throws CoreException
	{
		myfirstmodule.proxies.CarColor result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Selection_CarColor.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.CarColor.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Selection_CarColor
	 * @param selection_carcolor
	 */
	public final void setSelection_CarColor(myfirstmodule.proxies.CarColor selection_carcolor)
	{
		setSelection_CarColor(getContext(), selection_carcolor);
	}

	/**
	 * Set value of Selection_CarColor
	 * @param context
	 * @param selection_carcolor
	 */
	public final void setSelection_CarColor(IContext context, myfirstmodule.proxies.CarColor selection_carcolor)
	{
		if (selection_carcolor == null)
			getMendixObject().setValue(context, MemberNames.Selection_CarColor.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Selection_CarColor.toString(), selection_carcolor.getMendixObject().getId());
	}

	/**
	 * @return value of AppFlow_Account
	 */
	public final administration.proxies.Account getAppFlow_Account() throws CoreException
	{
		return getAppFlow_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of AppFlow_Account
	 */
	public final administration.proxies.Account getAppFlow_Account(IContext context) throws CoreException
	{
		administration.proxies.Account result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AppFlow_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AppFlow_Account
	 * @param appflow_account
	 */
	public final void setAppFlow_Account(administration.proxies.Account appflow_account)
	{
		setAppFlow_Account(getContext(), appflow_account);
	}

	/**
	 * Set value of AppFlow_Account
	 * @param context
	 * @param appflow_account
	 */
	public final void setAppFlow_Account(IContext context, administration.proxies.Account appflow_account)
	{
		if (appflow_account == null)
			getMendixObject().setValue(context, MemberNames.AppFlow_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AppFlow_Account.toString(), appflow_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return appFlowMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.AppFlow that = (myfirstmodule.proxies.AppFlow) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.AppFlow";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
