// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class CarColor
{
	private final IMendixObject carColorMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.CarColor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		CarColor_CarColorImage("MyFirstModule.CarColor_CarColorImage"),
		ColorCar_Car("MyFirstModule.ColorCar_Car");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public CarColor(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.CarColor"));
	}

	protected CarColor(IContext context, IMendixObject carColorMendixObject)
	{
		if (carColorMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.CarColor", carColorMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.CarColor");

		this.carColorMendixObject = carColorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CarColor.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.CarColor initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.CarColor.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.CarColor initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CarColor(context, mendixObject);
	}

	public static myfirstmodule.proxies.CarColor load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CarColor.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CarColor> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.CarColor> result = new java.util.ArrayList<myfirstmodule.proxies.CarColor>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.CarColor" + xpathConstraint))
			result.add(myfirstmodule.proxies.CarColor.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of CarColor_CarColorImage
	 */
	public final myfirstmodule.proxies.CarColorImage getCarColor_CarColorImage() throws CoreException
	{
		return getCarColor_CarColorImage(getContext());
	}

	/**
	 * @param context
	 * @return value of CarColor_CarColorImage
	 */
	public final myfirstmodule.proxies.CarColorImage getCarColor_CarColorImage(IContext context) throws CoreException
	{
		myfirstmodule.proxies.CarColorImage result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CarColor_CarColorImage.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.CarColorImage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CarColor_CarColorImage
	 * @param carcolor_carcolorimage
	 */
	public final void setCarColor_CarColorImage(myfirstmodule.proxies.CarColorImage carcolor_carcolorimage)
	{
		setCarColor_CarColorImage(getContext(), carcolor_carcolorimage);
	}

	/**
	 * Set value of CarColor_CarColorImage
	 * @param context
	 * @param carcolor_carcolorimage
	 */
	public final void setCarColor_CarColorImage(IContext context, myfirstmodule.proxies.CarColorImage carcolor_carcolorimage)
	{
		if (carcolor_carcolorimage == null)
			getMendixObject().setValue(context, MemberNames.CarColor_CarColorImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CarColor_CarColorImage.toString(), carcolor_carcolorimage.getMendixObject().getId());
	}

	/**
	 * @return value of ColorCar_Car
	 */
	public final myfirstmodule.proxies.Car getColorCar_Car() throws CoreException
	{
		return getColorCar_Car(getContext());
	}

	/**
	 * @param context
	 * @return value of ColorCar_Car
	 */
	public final myfirstmodule.proxies.Car getColorCar_Car(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Car result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ColorCar_Car.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Car.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ColorCar_Car
	 * @param colorcar_car
	 */
	public final void setColorCar_Car(myfirstmodule.proxies.Car colorcar_car)
	{
		setColorCar_Car(getContext(), colorcar_car);
	}

	/**
	 * Set value of ColorCar_Car
	 * @param context
	 * @param colorcar_car
	 */
	public final void setColorCar_Car(IContext context, myfirstmodule.proxies.Car colorcar_car)
	{
		if (colorcar_car == null)
			getMendixObject().setValue(context, MemberNames.ColorCar_Car.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ColorCar_Car.toString(), colorcar_car.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return carColorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CarColor that = (myfirstmodule.proxies.CarColor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.CarColor";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
