// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class CoachworkImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.CoachworkImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Coachwork_CoachworkImage("MyFirstModule.Coachwork_CoachworkImage");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public CoachworkImage(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.CoachworkImage"));
	}

	protected CoachworkImage(IContext context, IMendixObject coachworkImageMendixObject)
	{
		super(context, coachworkImageMendixObject);
		if (!Core.isSubClassOf("MyFirstModule.CoachworkImage", coachworkImageMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.CoachworkImage");
	}

	/**
	 * @deprecated Use 'CoachworkImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.CoachworkImage initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.CoachworkImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.CoachworkImage initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CoachworkImage(context, mendixObject);
	}

	public static myfirstmodule.proxies.CoachworkImage load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CoachworkImage.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CoachworkImage> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.CoachworkImage> result = new java.util.ArrayList<myfirstmodule.proxies.CoachworkImage>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.CoachworkImage" + xpathConstraint))
			result.add(myfirstmodule.proxies.CoachworkImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Coachwork_CoachworkImage
	 */
	public final myfirstmodule.proxies.Coachwork getCoachwork_CoachworkImage() throws CoreException
	{
		return getCoachwork_CoachworkImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Coachwork_CoachworkImage
	 */
	public final myfirstmodule.proxies.Coachwork getCoachwork_CoachworkImage(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Coachwork result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coachwork_CoachworkImage.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Coachwork.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Coachwork_CoachworkImage
	 * @param coachwork_coachworkimage
	 */
	public final void setCoachwork_CoachworkImage(myfirstmodule.proxies.Coachwork coachwork_coachworkimage)
	{
		setCoachwork_CoachworkImage(getContext(), coachwork_coachworkimage);
	}

	/**
	 * Set value of Coachwork_CoachworkImage
	 * @param context
	 * @param coachwork_coachworkimage
	 */
	public final void setCoachwork_CoachworkImage(IContext context, myfirstmodule.proxies.Coachwork coachwork_coachworkimage)
	{
		if (coachwork_coachworkimage == null)
			getMendixObject().setValue(context, MemberNames.Coachwork_CoachworkImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Coachwork_CoachworkImage.toString(), coachwork_coachworkimage.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CoachworkImage that = (myfirstmodule.proxies.CoachworkImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.CoachworkImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
